# Generated by Django 4.0.4 on 2022-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolists',
            name='status',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
